name: Run Backend Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: localhost
          POSTGRES_PASSWORD: localhost
          POSTGRES_DB: slms-test
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install poetry
        working-directory: backend/
        run: |
          pip install --upgrade pip
          pip install poetry

      - name: Install Dependencies
        working-directory: backend/
        run: |
          poetry install

      - name: Run Tests
        working-directory: backend/
        env:
          # pydantic-settings will use this URI over the value passed in test.env
          DB_URI: "postgresql+asyncpg://localhost:localhost@localhost:${{ job.services.postgres.ports[5432] }}/slms-test"
        run: |
          APP_CONFIG=test pytest .
